// THE REGISTRY OF CAREER BOARDS
//
// One company per line: its identifier at its ATS, and the name a candidate
// recognises. This is the one part of the feature that is not written but
// built: reading a board is trivial, knowing it exists is not. For the same
// reason it is the only part that protects anything.
//
// The first list was verified on 6 October 2026: a hundred and eighteen
// company names guessed by hand, tried against the six ATSs, forty-nine live
// boards and close to four thousand jobs. A forty percent hit rate on
// guesses, which mostly says how much is left to find.
//
// TO GROW IT: node scripts/find-job-boards.mjs --hn --market gb
//
// The script verifies every line before writing it. Nothing here is guessed:
// a line present is a line whose board answered, in the right market, and
// said whose it was.

export const BOARDS = [
  { slug: "stripe", ats: "greenhouse", name: "Stripe" },
  { slug: "elastic", ats: "greenhouse", name: "Elastic" },
  { slug: "sumup", ats: "greenhouse", name: "SumUp" },
  { slug: "palantir", ats: "lever", name: "Palantir" },
  { slug: "canonical", ats: "greenhouse", name: "Canonical" },
  { slug: "gitlab", ats: "greenhouse", name: "GitLab" },
  { slug: "deliveroo", ats: "greenhouse", name: "Deliveroo" },
  { slug: "graphcore", ats: "greenhouse", name: "Graphcore" },
  { slug: "ebury", ats: "greenhouse", name: "Ebury" },
  { slug: "airbnb", ats: "greenhouse", name: "Airbnb" },
  { slug: "wayve", ats: "ashby", name: "Wayve" },
  { slug: "payoneer", ats: "greenhouse", name: "Payoneer" },
  { slug: "tide", ats: "greenhouse", name: "Tide" },
  { slug: "spotify", ats: "lever", name: "Spotify" },
  { slug: "faculty", ats: "ashby", name: "Faculty" },
  { slug: "monzo", ats: "greenhouse", name: "Monzo" },
  { slug: "getyourguide", ats: "greenhouse", name: "GetYourGuide" },
  { slug: "n26", ats: "greenhouse", name: "N26" },
  { slug: "trustpilot", ats: "greenhouse", name: "Trustpilot" },
  { slug: "farfetch", ats: "lever", name: "Farfetch" },
  { slug: "quantexa", ats: "ashby", name: "Quantexa" },
  { slug: "zopa", ats: "lever", name: "Zopa" },
  { slug: "trainline", ats: "ashby", name: "Trainline" },
  { slug: "pleo", ats: "ashby", name: "Pleo" },
  { slug: "primer", ats: "ashby", name: "Primer" },
  { slug: "gocardless", ats: "greenhouse", name: "GoCardless" },
  { slug: "moneybox", ats: "ashby", name: "Moneybox" },
  { slug: "elliptic", ats: "ashby", name: "Elliptic" },
  { slug: "paddle", ats: "ashby", name: "Paddle" },
  { slug: "multiverse", ats: "ashby", name: "Multiverse" },
  { slug: "snyk", ats: "ashby", name: "Snyk" },
  { slug: "wise", ats: "greenhouse", name: "Wise" },
  { slug: "typeform", ats: "greenhouse", name: "Typeform" },
  { slug: "zilch", ats: "ashby", name: "Zilch" },
  { slug: "marshmallow", ats: "ashby", name: "Marshmallow" },
  { slug: "mindfoundry", ats: "greenhouse", name: "Mind Foundry" },
  { slug: "immersivelabs", ats: "ashby", name: "Immersive Labs" },
  { slug: "form3", ats: "greenhouse", name: "Form3" },
  { slug: "griffin", ats: "ashby", name: "Griffin" },
  { slug: "freetrade", ats: "ashby", name: "Freetrade" },
  { slug: "signal-ai", ats: "ashby", name: "Signal AI" },
  { slug: "beamery", ats: "ashby", name: "Beamery" },
  { slug: "copperco", ats: "greenhouse", name: "Copper" },
  { slug: "improbable", ats: "ashby", name: "Improbable" },
  { slug: "truelayer", ats: "greenhouse", name: "TrueLayer" },
  { slug: "cleo", ats: "greenhouse", name: "Cleo" },
  { slug: "ovoenergy", ats: "greenhouse", name: "OVO Energy" },
  { slug: "unmind", ats: "ashby", name: "Unmind" },
  { slug: "personio", ats: "recruitee", name: "Personio" },
  { slug: "wpp", ats: "greenhouse", name: "WPP", market: "gb" },
  { slug: "metropolis", ats: "greenhouse", name: "Metropolis", market: "gb" },
  { slug: "map", ats: "greenhouse", name: "MAP", market: "gb" },
  { slug: "framestore", ats: "recruitee", name: "Framestore", market: "gb" },
  { slug: "swire", ats: "recruitee", name: "Swire", market: "gb" },
  { slug: "moss", ats: "ashby", name: "Moss", market: "gb" },
  { slug: "mintel", ats: "greenhouse", name: "Mintel", market: "gb" },
  { slug: "zeal-network", ats: "ashby", name: "Zeal Network", market: "gb" },
  { slug: "inizio", ats: "greenhouse", name: "Inizio", market: "gb" },
  { slug: "cube", ats: "ashby", name: "CUBE", market: "gb" },
  { slug: "eunetworks", ats: "greenhouse", name: "euNetworks", market: "gb" },
  { slug: "moonpig", ats: "lever", name: "Moonpig", market: "gb" },
  { slug: "janes", ats: "greenhouse", name: "Janes", market: "gb" },
  { slug: "storiogroup", ats: "lever", name: "Storio group", market: "gb" },
  { slug: "ifrsfoundation", ats: "greenhouse", name: "IFRS Foundation", market: "gb" },
  { slug: "clearbank", ats: "ashby", name: "ClearBank", market: "gb" },
  { slug: "mec", ats: "recruitee", name: "MEC Consulting Group", market: "gb" },
  { slug: "dmgt", ats: "greenhouse", name: "DMGT", market: "gb" },
  { slug: "ikpartners", ats: "recruitee", name: "IK Partners", market: "gb" },
  { slug: "bcpartners", ats: "recruitee", name: "BC Partners", market: "gb" },
  { slug: "octoenergy", ats: "lever", name: "Octopus Energy Group", market: "gb" },
  { slug: "thesocialhub", ats: "greenhouse", name: "The Social Hub", market: "gb" },
  { slug: "sophos", ats: "lever", name: "Sophos", market: "gb" },
  { slug: "castrol", ats: "greenhouse", name: "Castrol", market: "gb" },
  { slug: "mulberry", ats: "lever", name: "Mulberry", market: "gb" },
  { slug: "joblogic", ats: "greenhouse", name: "Joblogic", market: "gb" },
  { slug: "headfirst", ats: "recruitee", name: "Vertage", market: "gb" },
  { slug: "searchable", ats: "ashby", name: "Searchable", market: "gb" },
  { slug: "red-gate", ats: "ashby", name: "Redgate", market: "gb" },
  { slug: "exclaimer", ats: "greenhouse", name: "Exclaimer", market: "gb" },
  { slug: "foundry", ats: "greenhouse", name: "Foundry", market: "gb" },
  { slug: "elsevier", ats: "greenhouse", name: "Elsevier", market: "gb" },
  { slug: "policyexpert", ats: "greenhouse", name: "Policy Expert", market: "gb" },
  { slug: "bromcom", ats: "recruitee", name: "Bromcom Computers Plc", market: "gb" },
  { slug: "rubix", ats: "greenhouse", name: "Rubix", market: "gb" },
  { slug: "nothing", ats: "greenhouse", name: "Nothing", market: "gb" },
  { slug: "thinkmarkets", ats: "greenhouse", name: "ThinkMarkets", market: "gb" },
  { slug: "notpla", ats: "personio", name: "Notpla Limited", market: "gb" },
  { slug: "apax", ats: "recruitee", name: "Apax", market: "gb" },
  { slug: "validsoft", ats: "personio", name: "ValidSoft", market: "gb" },
  { slug: "blacks", ats: "greenhouse", name: "Blacks", market: "gb" },
  { slug: "nmcareers", ats: "greenhouse", name: "NaturalMotion", market: "gb" },
  { slug: "dovetailgames", ats: "recruitee", name: "Dovetail Games Ltd", market: "gb" },
  { slug: "firesprite", ats: "greenhouse", name: "Firesprite", market: "gb" },
  { slug: "shemed", ats: "greenhouse", name: "SheMed", market: "gb" },

  { slug: "andurilindustries", ats: "greenhouse", name: "Anduril Industries", market: "gb" },
  { slug: "shieldai", ats: "lever", name: "Shield AI", market: "gb" },
  { slug: "lyrahealth", ats: "lever", name: "Lyra Health", market: "gb" },
  { slug: "braze", ats: "greenhouse", name: "Braze", market: "gb" },
  { slug: "okx", ats: "greenhouse", name: "OKX", market: "gb" },
  { slug: "coreweave", ats: "greenhouse", name: "CoreWeave", market: "gb" },
  { slug: "verkada", ats: "greenhouse", name: "Verkada", market: "gb" },
  { slug: "xai", ats: "greenhouse", name: "SpaceXAI", market: "gb" },
  { slug: "fluidstack", ats: "ashby", name: "Fluidstack", market: "gb" },
  { slug: "samsara", ats: "greenhouse", name: "Samsara", market: "gb" },
  { slug: "zoox", ats: "lever", name: "Zoox", market: "gb" },
  { slug: "adyen", ats: "greenhouse", name: "Adyen", market: "gb" },
  { slug: "natera", ats: "greenhouse", name: "Natera", market: "gb" },
  { slug: "icapitalnetwork", ats: "greenhouse", name: "iCapital", market: "gb" },
  { slug: "sonyinteractiveentertainmentglobal", ats: "greenhouse", name: "PlayStation Global", market: "gb" },
  { slug: "clickhouse", ats: "ashby", name: "ClickHouse", market: "gb" },
  { slug: "tether", ats: "recruitee", name: "Tether Operations Limited", market: "gb" },
  { slug: "affirm", ats: "greenhouse", name: "Affirm", market: "gb" },
  { slug: "via", ats: "greenhouse", name: "Via", market: "gb" },
  { slug: "figma", ats: "greenhouse", name: "Figma", market: "gb" },
  { slug: "ramp", ats: "ashby", name: "Ramp", market: "gb" },
  { slug: "robinhood", ats: "greenhouse", name: "Robinhood", market: "gb" },
  { slug: "reddit", ats: "greenhouse", name: "Reddit", market: "gb" },
  { slug: "archer56", ats: "greenhouse", name: "Archer", market: "gb" },
  { slug: "thenewyorktimes", ats: "greenhouse", name: "The New York Times", market: "gb" },
  { slug: "twilio", ats: "greenhouse", name: "Twilio", market: "gb" },
  { slug: "grafanalabs", ats: "greenhouse", name: "Grafana Labs", market: "gb" },
  { slug: "ripple", ats: "greenhouse", name: "Ripple", market: "gb" },
  { slug: "ionq", ats: "greenhouse", name: "IonQ", market: "gb" },
  { slug: "boxinc", ats: "greenhouse", name: "Box", market: "gb" },
  { slug: "flagshippioneeringinc", ats: "greenhouse", name: "Flagship Pioneering, Inc.", market: "gb" },
  { slug: "planetlabs", ats: "greenhouse", name: "Planet", market: "gb" },
  { slug: "mercor", ats: "ashby", name: "Mercor", market: "gb" },
  { slug: "addepar1", ats: "greenhouse", name: "Addepar", market: "gb" },
  { slug: "intercom", ats: "greenhouse", name: "Fin", market: "gb" },
  { slug: "baseten", ats: "ashby", name: "Baseten", market: "gb" },
  { slug: "tripadvisor", ats: "greenhouse", name: "Tripadvisor", market: "gb" },
  { slug: "opentable", ats: "greenhouse", name: "OpenTable", market: "gb" },
  { slug: "pear-vc", ats: "ashby", name: "Pear VC", market: "gb" },
  { slug: "justworks", ats: "greenhouse", name: "Justworks", market: "gb" },
  { slug: "peregrinetechnologies", ats: "greenhouse", name: "Peregrine Technologies", market: "gb" },
  { slug: "crunchyroll", ats: "greenhouse", name: "Crunchyroll, LLC", market: "gb" },
  { slug: "penumbrainc", ats: "lever", name: "Penumbra", market: "gb" },
  { slug: "carta", ats: "greenhouse", name: "Carta", market: "gb" },
  { slug: "kong", ats: "ashby", name: "Kong", market: "gb" },
  { slug: "alpaca", ats: "greenhouse", name: "Alpaca", market: "gb" },
  { slug: "matchgroup", ats: "lever", name: "Match Group", market: "gb" },
  { slug: "replit", ats: "ashby", name: "Replit", market: "gb" },
  { slug: "sigmacomputing", ats: "greenhouse", name: "Sigma Computing", market: "gb" },
  { slug: "suno", ats: "ashby", name: "Suno", market: "gb" },
  { slug: "knowbe4", ats: "greenhouse", name: "KnowBe4", market: "gb" },
  { slug: "sothebys", ats: "greenhouse", name: "Sotheby's", market: "gb" },
  { slug: "krakentech", ats: "ashby", name: "Kraken", market: "gb" },
  { slug: "duolingo", ats: "greenhouse", name: "Duolingo", market: "gb" },
  { slug: "peloton", ats: "greenhouse", name: "Peloton", market: "gb" },
  { slug: "mixpanel", ats: "greenhouse", name: "Mixpanel", market: "gb" },
  { slug: "launchdarkly", ats: "greenhouse", name: "LaunchDarkly", market: "gb" },
  { slug: "tailscale", ats: "greenhouse", name: "Tailscale", market: "gb" },
  { slug: "lightningai", ats: "greenhouse", name: "Lightning AI", market: "gb" },
  { slug: "writer", ats: "ashby", name: "WRITER", market: "gb" },
  { slug: "supabase", ats: "ashby", name: "Supabase", market: "gb" },
  { slug: "humansignal", ats: "greenhouse", name: "HumanSignal", market: "gb" },
  { slug: "virtu", ats: "greenhouse", name: "Virtu Financial", market: "gb" },
  { slug: "coram-ai", ats: "ashby", name: "Coram AI", market: "gb" },
  { slug: "qualtrics", ats: "greenhouse", name: "Qualtrics", market: "gb" },
  { slug: "relex", ats: "greenhouse", name: "RELEX Solutions", market: "gb" },
  { slug: "mendix", ats: "lever", name: "Mendix", market: "gb" },
  { slug: "clearstreet", ats: "greenhouse", name: "Clear Street", market: "gb" },
  { slug: "runway-ml", ats: "ashby", name: "Runway", market: "gb" },
  { slug: "verve", ats: "greenhouse", name: "Verve", market: "gb" },
  { slug: "mapbox", ats: "ashby", name: "Mapbox", market: "gb" },
  { slug: "algolia", ats: "greenhouse", name: "Algolia", market: "gb" },
  { slug: "modal", ats: "ashby", name: "Modal", market: "gb" },
  { slug: "canarytechnologies", ats: "lever", name: "Canary Technologies Corp", market: "gb" },
  { slug: "datacamp", ats: "greenhouse", name: "DataCamp", market: "gb" },
  { slug: "tenableinc", ats: "greenhouse", name: "Tenable, Inc.", market: "gb" },
  { slug: "commercetools", ats: "greenhouse", name: "commercetools", market: "gb" },
  { slug: "hudl", ats: "greenhouse", name: "Hudl", market: "gb" },
  { slug: "coupa", ats: "lever", name: "Coupa Software, Inc.", market: "gb" },
  { slug: "ironcladhq", ats: "ashby", name: "Ironclad", market: "gb" },
  { slug: "koboldmetals", ats: "greenhouse", name: "KoBold Metals", market: "gb" },
  { slug: "classpass", ats: "greenhouse", name: "ClassPass", market: "gb" },
  { slug: "floqast", ats: "lever", name: "FloQast", market: "gb" },
  { slug: "gigaml", ats: "ashby", name: "Giga", market: "gb" },
  { slug: "taketwo", ats: "greenhouse", name: "Take-Two Interactive Software, Inc.", market: "gb" },
  { slug: "fender", ats: "greenhouse", name: "Fender", market: "gb" },
  { slug: "aptura", ats: "ashby", name: "Aptura", market: "gb" },
  { slug: "rilla", ats: "ashby", name: "Rilla", market: "gb" },
  { slug: "livekit", ats: "ashby", name: "LiveKit", market: "gb" },
  { slug: "blacksky", ats: "greenhouse", name: "BlackSky", market: "gb" },
  { slug: "censys", ats: "greenhouse", name: "Censys", market: "gb" },
  { slug: "coder", ats: "ashby", name: "Coder", market: "gb" },
  { slug: "socket", ats: "ashby", name: "Socket", market: "gb" },
  { slug: "outreach", ats: "lever", name: "Outreach", market: "gb" },
  { slug: "convergentresearch", ats: "lever", name: "Convergent Research", market: "gb" },
  { slug: "contentsquare", ats: "lever", name: "Contentsquare", market: "gb" },
  { slug: "astronomer", ats: "ashby", name: "Astronomer", market: "gb" },
  { slug: "alayacare", ats: "greenhouse", name: "AlayaCare", market: "gb" },
  { slug: "behavox", ats: "greenhouse", name: "Behavox", market: "gb" },
  { slug: "distyl", ats: "ashby", name: "Distyl AI", market: "gb" },
  { slug: "antithesis", ats: "ashby", name: "Antithesis", market: "gb" },
  { slug: "pendo", ats: "greenhouse", name: "Pendo", market: "gb" },
  { slug: "g2i", ats: "ashby", name: "G2i Inc.", market: "gb" },
  { slug: "bazaarvoice", ats: "lever", name: "Bazaarvoice", market: "gb" },
  { slug: "triplelift", ats: "greenhouse", name: "TripleLift", market: "gb" },
  { slug: "dominodatalab", ats: "greenhouse", name: "Domino", market: "gb" },
  { slug: "oscilar", ats: "ashby", name: "Oscilar", market: "gb" },
  { slug: "ember", ats: "recruitee", name: "Ember", market: "gb" },
  { slug: "contentful", ats: "greenhouse", name: "Contentful", market: "gb" },
  { slug: "norm-ai", ats: "ashby", name: "Norm Ai", market: "gb" },
  { slug: "airops", ats: "ashby", name: "AirOps", market: "gb" },
  { slug: "altanaai", ats: "greenhouse", name: "Altana", market: "gb" },
  { slug: "protege", ats: "ashby", name: "Protege", market: "gb" },
  { slug: "orkes", ats: "greenhouse", name: "Orkes", market: "gb" },
  { slug: "appzen", ats: "lever", name: "AppZen, Inc.", market: "gb" },
  { slug: "mercanis", ats: "personio", name: "Mercanis", market: "gb" },
  { slug: "prematch-sports-gmbh", ats: "personio", name: "PREMATCH Sports GmbH", market: "gb" },
  { slug: "deepl", ats: "ashby", name: "DeepL", market: "gb" },
  { slug: "hiya", ats: "ashby", name: "Hiya", market: "gb" },
  { slug: "q-ctrl", ats: "lever", name: "Q-CTRL", market: "gb" },
  { slug: "rigetti", ats: "lever", name: "Rigetti Computing", market: "gb" },
  { slug: "liveeo-gmbh", ats: "personio", name: "Jobs bei LiveEO GmbH", market: "gb" },
  { slug: "harrys", ats: "greenhouse", name: "Harry's", market: "gb" },
  { slug: "ontic", ats: "ashby", name: "Ontic", market: "gb" },
  { slug: "sona", ats: "ashby", name: "Sona", market: "gb" },
  { slug: "soundcloud71", ats: "greenhouse", name: "SoundCloud", market: "gb" },
  { slug: "obsidiansecurity", ats: "greenhouse", name: "Obsidian Security", market: "gb" },
  { slug: "theathletic", ats: "lever", name: "The Athletic Media Company", market: "gb" },
  { slug: "signifyd95", ats: "greenhouse", name: "Signifyd", market: "gb" },
  { slug: "akur8", ats: "ashby", name: "Akur8", market: "gb" },
  { slug: "mattermost", ats: "greenhouse", name: "Mattermost", market: "gb" },
  { slug: "olo", ats: "lever", name: "Olo", market: "gb" },
  { slug: "immuta", ats: "lever", name: "Immuta", market: "gb" },
  { slug: "ideo", ats: "greenhouse", name: "IDEO", market: "gb" },
  { slug: "apolloresearch", ats: "lever", name: "Apollo Research", market: "gb" },
  { slug: "humaans", ats: "ashby", name: "Humaans", market: "gb" },
  { slug: "merantix", ats: "personio", name: "Merantix", market: "gb" },
  { slug: "muckrack", ats: "greenhouse", name: "Muck Rack", market: "gb" },
  { slug: "brave", ats: "greenhouse", name: "Brave", market: "gb" },
  { slug: "axle-careers", ats: "ashby", name: "Axle Energy", market: "gb" },
  { slug: "avantarte", ats: "recruitee", name: "Avant Arte", market: "gb" },
  { slug: "engineersgate", ats: "greenhouse", name: "Engineers Gate", market: "gb" },
  { slug: "fanvue.com", ats: "ashby", name: "Fanvue", market: "gb" },
  { slug: "buildkite", ats: "greenhouse", name: "Buildkite", market: "gb" },
  { slug: "sumologic", ats: "greenhouse", name: "Sumo Logic", market: "gb" },
  { slug: "quantummetric", ats: "lever", name: "Quantum Metric", market: "gb" },
  { slug: "patch.io", ats: "ashby", name: "Patch", market: "gb" },
  { slug: "ditto", ats: "ashby", name: "Ditto", market: "gb" },
  { slug: "anima", ats: "ashby", name: "Anima", market: "gb" },
  { slug: "smarkets", ats: "ashby", name: "Smarkets", market: "gb" },
  { slug: "splice", ats: "greenhouse", name: "Splice", market: "gb" },
  { slug: "pathstream", ats: "greenhouse", name: "Pathstream", market: "gb" },
  { slug: "cordial81", ats: "greenhouse", name: "Cordial Experience Inc.", market: "gb" },
  { slug: "meticulous", ats: "ashby", name: "Meticulous", market: "gb" },
  { slug: "triggerdev", ats: "ashby", name: "Trigger.dev", market: "gb" },
  { slug: "pexa", ats: "lever", name: "PEXA Group", market: "gb" },
  { slug: "evervault", ats: "ashby", name: "Evervault", market: "gb" },
  { slug: "v7labs.com", ats: "ashby", name: "V7", market: "gb" },
  { slug: "electric-twin", ats: "lever", name: "Electric Twin", market: "gb" },
  { slug: "blacklane", ats: "greenhouse", name: "BLACKLANE", market: "gb" },
  { slug: "aurosglobal", ats: "greenhouse", name: "Auros", market: "gb" },
  { slug: "voldex", ats: "ashby", name: "Voldex Games", market: "gb" },
  { slug: "causalens", ats: "recruitee", name: "causaLens", market: "gb" },
  { slug: "pod-network", ats: "ashby", name: "pod.network", market: "gb" },
  { slug: "speckle", ats: "ashby", name: "Speckle", market: "gb" },
  { slug: "lightdash", ats: "ashby", name: "Lightdash", market: "gb" },
  { slug: "ameba", ats: "ashby", name: "Ameba", market: "gb" },
  { slug: "tilt", ats: "ashby", name: "Tilt", market: "gb" },
  { slug: "materiom", ats: "greenhouse", name: "Materiom", market: "gb" },
  { slug: "herdify", ats: "personio", name: "Herdify", market: "gb" },
  { slug: "mubit", ats: "ashby", name: "Mubit", market: "gb" },
  { slug: "sezzle", ats: "greenhouse", name: "Sezzle", market: "fr" },
  { slug: "flexport", ats: "greenhouse", name: "Flexport", market: "fr" },
  { slug: "loftorbital", ats: "lever", name: "Loft Orbital Solutions", market: "fr" },
  { slug: "backmarket", ats: "ashby", name: "Back Market", market: "fr" },
  { slug: "amo", ats: "ashby", name: "amo", market: "fr" },
  { slug: "godaddy", ats: "greenhouse", name: "GoDaddy", market: "fr" },
  { slug: "beaconbiosignals", ats: "greenhouse", name: "Beacon Biosignals", market: "fr" },
  { slug: "prelude", ats: "ashby", name: "Prelude", market: "fr" },
  { slug: "blablacar", ats: "lever", name: "BlaBlaCar", market: "fr" },
  { slug: "frontcareers", ats: "ashby", name: "Front", market: "fr" },
  { slug: "coderpad", ats: "lever", name: "CoderPad", market: "fr" },
  { slug: "vestiairecollective", ats: "lever", name: "Vestiaire Collective", market: "fr" },
  { slug: "exnaton-ag", ats: "personio", name: "exnaton AG", market: "fr" },
  { slug: "scality", ats: "lever", name: "Scality", market: "fr" },
  { slug: "konvu", ats: "ashby", name: "Konvu", market: "fr" },
  { slug: "opsmill", ats: "ashby", name: "OpsMill", market: "fr" },
  { slug: "upflow", ats: "ashby", name: "Upflow", market: "fr" },
];

export function boardsByAts(nom) {
  return BOARDS.filter((b) => b.ats === nom);
}

// A BOARD WITH NO `market` PREDATES THE FIELD
//
// The first forty-nine lines were verified by hand, one at a time, and
// several of them are companies that hire everywhere. So they are tried for
// every market: a field that gets added must never remove a line from a
// search that found it yesterday.
//
// For the ones after that, the market is what makes scale possible. A London
// search has no reason to read the German boards, and that is the difference
// between a registry of five hundred lines and one that can carry thousands.
//
// This function sits AFTER boardsByAts rather than before, because the
// discovery scripts insert their lines immediately ahead of it: the string
// "];\n\nexport function boardsByAts" is their anchor, and slipping anything
// in there makes them refuse to write.
export function boardsForMarket(code) {
  const c = String(code || "").toLowerCase();
  return BOARDS.filter((b) => !b.market || b.market === c);
}

export function companyName(slug) {
  const b = BOARDS.find((x) => x.slug === slug);
  return (b && b.name) || slug;
}
