// LE REGISTRE DES TABLEAUX D'OFFRES
//
// Une entreprise par ligne : son identifiant chez son ATS, et le nom qu'un
// candidat reconnait. C'est la seule partie de cette fonctionnalite qui ne
// s'ecrit pas, qui se construit : lire un tableau est trivial, savoir qu'il
// existe ne l'est pas. C'est aussi, pour cette raison, la seule qui protege.
//
// Cette premiere liste a ete verifiee le 6 octobre 2026 : cent dix-huit noms
// d'entreprise devines a la main, essayes contre les six ATS, quarante-neuf
// tableaux vivants et pres de quatre mille postes. Un taux de reussite de
// quarante pour cent sur des devinettes, ce qui dit surtout combien il reste
// a trouver.
//
// POUR L'ALLONGER : node scripts/decouvrir-des-boards.mjs mes-candidats.txt
//
// Le script essaie chaque nom contre les six ATS et n'ecrit que ce qui
// repond avec au moins un poste. Rien ici n'est devine : une ligne presente
// est une ligne qui a repondu.

export const BOARDS = [
  { slug: "stripe", ats: "greenhouse", nom: "Stripe" },
  { slug: "elastic", ats: "greenhouse", nom: "Elastic" },
  { slug: "sumup", ats: "greenhouse", nom: "SumUp" },
  { slug: "palantir", ats: "lever", nom: "Palantir" },
  { slug: "canonical", ats: "greenhouse", nom: "Canonical" },
  { slug: "gitlab", ats: "greenhouse", nom: "GitLab" },
  { slug: "deliveroo", ats: "greenhouse", nom: "Deliveroo" },
  { slug: "graphcore", ats: "greenhouse", nom: "Graphcore" },
  { slug: "ebury", ats: "greenhouse", nom: "Ebury" },
  { slug: "airbnb", ats: "greenhouse", nom: "Airbnb" },
  { slug: "wayve", ats: "ashby", nom: "Wayve" },
  { slug: "payoneer", ats: "greenhouse", nom: "Payoneer" },
  { slug: "tide", ats: "greenhouse", nom: "Tide" },
  { slug: "spotify", ats: "lever", nom: "Spotify" },
  { slug: "faculty", ats: "ashby", nom: "Faculty" },
  { slug: "monzo", ats: "greenhouse", nom: "Monzo" },
  { slug: "getyourguide", ats: "greenhouse", nom: "GetYourGuide" },
  { slug: "n26", ats: "greenhouse", nom: "N26" },
  { slug: "trustpilot", ats: "greenhouse", nom: "Trustpilot" },
  { slug: "farfetch", ats: "lever", nom: "Farfetch" },
  { slug: "quantexa", ats: "ashby", nom: "Quantexa" },
  { slug: "zopa", ats: "lever", nom: "Zopa" },
  { slug: "trainline", ats: "ashby", nom: "Trainline" },
  { slug: "pleo", ats: "ashby", nom: "Pleo" },
  { slug: "primer", ats: "ashby", nom: "Primer" },
  { slug: "gocardless", ats: "greenhouse", nom: "GoCardless" },
  { slug: "moneybox", ats: "ashby", nom: "Moneybox" },
  { slug: "elliptic", ats: "ashby", nom: "Elliptic" },
  { slug: "paddle", ats: "ashby", nom: "Paddle" },
  { slug: "multiverse", ats: "ashby", nom: "Multiverse" },
  { slug: "snyk", ats: "ashby", nom: "Snyk" },
  { slug: "wise", ats: "greenhouse", nom: "Wise" },
  { slug: "typeform", ats: "greenhouse", nom: "Typeform" },
  { slug: "zilch", ats: "ashby", nom: "Zilch" },
  { slug: "marshmallow", ats: "ashby", nom: "Marshmallow" },
  { slug: "mindfoundry", ats: "greenhouse", nom: "Mind Foundry" },
  { slug: "immersivelabs", ats: "ashby", nom: "Immersive Labs" },
  { slug: "form3", ats: "greenhouse", nom: "Form3" },
  { slug: "griffin", ats: "ashby", nom: "Griffin" },
  { slug: "freetrade", ats: "ashby", nom: "Freetrade" },
  { slug: "signal-ai", ats: "ashby", nom: "Signal AI" },
  { slug: "beamery", ats: "ashby", nom: "Beamery" },
  { slug: "copperco", ats: "greenhouse", nom: "Copper" },
  { slug: "improbable", ats: "ashby", nom: "Improbable" },
  { slug: "truelayer", ats: "greenhouse", nom: "TrueLayer" },
  { slug: "cleo", ats: "greenhouse", nom: "Cleo" },
  { slug: "ovoenergy", ats: "greenhouse", nom: "OVO Energy" },
  { slug: "unmind", ats: "ashby", nom: "Unmind" },
  { slug: "personio", ats: "recruitee", nom: "Personio" },
  { slug: "wpp", ats: "greenhouse", nom: "WPP", marche: "gb" },
  { slug: "metropolis", ats: "greenhouse", nom: "Metropolis", marche: "gb" },
  { slug: "map", ats: "greenhouse", nom: "MAP", marche: "gb" },
  { slug: "framestore", ats: "recruitee", nom: "Framestore", marche: "gb" },
  { slug: "swire", ats: "recruitee", nom: "Swire", marche: "gb" },
  { slug: "moss", ats: "ashby", nom: "Moss", marche: "gb" },
  { slug: "mintel", ats: "greenhouse", nom: "Mintel", marche: "gb" },
  { slug: "zeal-network", ats: "ashby", nom: "Zeal Network", marche: "gb" },
  { slug: "inizio", ats: "greenhouse", nom: "Inizio", marche: "gb" },
  { slug: "cube", ats: "ashby", nom: "CUBE", marche: "gb" },
  { slug: "eunetworks", ats: "greenhouse", nom: "euNetworks", marche: "gb" },
  { slug: "moonpig", ats: "lever", nom: "Moonpig", marche: "gb" },
  { slug: "janes", ats: "greenhouse", nom: "Janes", marche: "gb" },
  { slug: "storiogroup", ats: "lever", nom: "Storio group", marche: "gb" },
  { slug: "ifrsfoundation", ats: "greenhouse", nom: "IFRS Foundation", marche: "gb" },
  { slug: "clearbank", ats: "ashby", nom: "ClearBank", marche: "gb" },
  { slug: "mec", ats: "recruitee", nom: "MEC Consulting Group", marche: "gb" },
  { slug: "dmgt", ats: "greenhouse", nom: "DMGT", marche: "gb" },
  { slug: "ikpartners", ats: "recruitee", nom: "IK Partners", marche: "gb" },
  { slug: "bcpartners", ats: "recruitee", nom: "BC Partners", marche: "gb" },
  { slug: "octoenergy", ats: "lever", nom: "Octopus Energy Group", marche: "gb" },
  { slug: "thesocialhub", ats: "greenhouse", nom: "The Social Hub", marche: "gb" },
  { slug: "sophos", ats: "lever", nom: "Sophos", marche: "gb" },
  { slug: "castrol", ats: "greenhouse", nom: "Castrol", marche: "gb" },
  { slug: "mulberry", ats: "lever", nom: "Mulberry", marche: "gb" },
  { slug: "joblogic", ats: "greenhouse", nom: "Joblogic", marche: "gb" },
  { slug: "headfirst", ats: "recruitee", nom: "Vertage", marche: "gb" },
  { slug: "searchable", ats: "ashby", nom: "Searchable", marche: "gb" },
  { slug: "red-gate", ats: "ashby", nom: "Redgate", marche: "gb" },
  { slug: "exclaimer", ats: "greenhouse", nom: "Exclaimer", marche: "gb" },
  { slug: "foundry", ats: "greenhouse", nom: "Foundry", marche: "gb" },
  { slug: "elsevier", ats: "greenhouse", nom: "Elsevier", marche: "gb" },
  { slug: "policyexpert", ats: "greenhouse", nom: "Policy Expert", marche: "gb" },
  { slug: "bromcom", ats: "recruitee", nom: "Bromcom Computers Plc", marche: "gb" },
  { slug: "rubix", ats: "greenhouse", nom: "Rubix", marche: "gb" },
  { slug: "nothing", ats: "greenhouse", nom: "Nothing", marche: "gb" },
  { slug: "thinkmarkets", ats: "greenhouse", nom: "ThinkMarkets", marche: "gb" },
  { slug: "notpla", ats: "personio", nom: "Notpla Limited", marche: "gb" },
  { slug: "apax", ats: "recruitee", nom: "Apax", marche: "gb" },
  { slug: "validsoft", ats: "personio", nom: "ValidSoft", marche: "gb" },
  { slug: "blacks", ats: "greenhouse", nom: "Blacks", marche: "gb" },
  { slug: "nmcareers", ats: "greenhouse", nom: "NaturalMotion", marche: "gb" },
  { slug: "dovetailgames", ats: "recruitee", nom: "Dovetail Games Ltd", marche: "gb" },
  { slug: "firesprite", ats: "greenhouse", nom: "Firesprite", marche: "gb" },
  { slug: "shemed", ats: "greenhouse", nom: "SheMed", marche: "gb" },

  { slug: "andurilindustries", ats: "greenhouse", nom: "Anduril Industries", marche: "gb" },
  { slug: "shieldai", ats: "lever", nom: "Shield AI", marche: "gb" },
  { slug: "lyrahealth", ats: "lever", nom: "Lyra Health", marche: "gb" },
  { slug: "braze", ats: "greenhouse", nom: "Braze", marche: "gb" },
  { slug: "okx", ats: "greenhouse", nom: "OKX", marche: "gb" },
  { slug: "coreweave", ats: "greenhouse", nom: "CoreWeave", marche: "gb" },
  { slug: "verkada", ats: "greenhouse", nom: "Verkada", marche: "gb" },
  { slug: "xai", ats: "greenhouse", nom: "SpaceXAI", marche: "gb" },
  { slug: "fluidstack", ats: "ashby", nom: "Fluidstack", marche: "gb" },
  { slug: "samsara", ats: "greenhouse", nom: "Samsara", marche: "gb" },
  { slug: "zoox", ats: "lever", nom: "Zoox", marche: "gb" },
  { slug: "adyen", ats: "greenhouse", nom: "Adyen", marche: "gb" },
  { slug: "natera", ats: "greenhouse", nom: "Natera", marche: "gb" },
  { slug: "icapitalnetwork", ats: "greenhouse", nom: "iCapital", marche: "gb" },
  { slug: "sonyinteractiveentertainmentglobal", ats: "greenhouse", nom: "PlayStation Global", marche: "gb" },
  { slug: "clickhouse", ats: "ashby", nom: "ClickHouse", marche: "gb" },
  { slug: "tether", ats: "recruitee", nom: "Tether Operations Limited", marche: "gb" },
  { slug: "affirm", ats: "greenhouse", nom: "Affirm", marche: "gb" },
  { slug: "via", ats: "greenhouse", nom: "Via", marche: "gb" },
  { slug: "figma", ats: "greenhouse", nom: "Figma", marche: "gb" },
  { slug: "ramp", ats: "ashby", nom: "Ramp", marche: "gb" },
  { slug: "robinhood", ats: "greenhouse", nom: "Robinhood", marche: "gb" },
  { slug: "reddit", ats: "greenhouse", nom: "Reddit", marche: "gb" },
  { slug: "archer56", ats: "greenhouse", nom: "Archer", marche: "gb" },
  { slug: "thenewyorktimes", ats: "greenhouse", nom: "The New York Times", marche: "gb" },
  { slug: "twilio", ats: "greenhouse", nom: "Twilio", marche: "gb" },
  { slug: "grafanalabs", ats: "greenhouse", nom: "Grafana Labs", marche: "gb" },
  { slug: "ripple", ats: "greenhouse", nom: "Ripple", marche: "gb" },
  { slug: "ionq", ats: "greenhouse", nom: "IonQ", marche: "gb" },
  { slug: "boxinc", ats: "greenhouse", nom: "Box", marche: "gb" },
  { slug: "flagshippioneeringinc", ats: "greenhouse", nom: "Flagship Pioneering, Inc.", marche: "gb" },
  { slug: "planetlabs", ats: "greenhouse", nom: "Planet", marche: "gb" },
  { slug: "mercor", ats: "ashby", nom: "Mercor", marche: "gb" },
  { slug: "addepar1", ats: "greenhouse", nom: "Addepar", marche: "gb" },
  { slug: "intercom", ats: "greenhouse", nom: "Fin", marche: "gb" },
  { slug: "baseten", ats: "ashby", nom: "Baseten", marche: "gb" },
  { slug: "tripadvisor", ats: "greenhouse", nom: "Tripadvisor", marche: "gb" },
  { slug: "opentable", ats: "greenhouse", nom: "OpenTable", marche: "gb" },
  { slug: "pear-vc", ats: "ashby", nom: "Pear VC", marche: "gb" },
  { slug: "justworks", ats: "greenhouse", nom: "Justworks", marche: "gb" },
  { slug: "peregrinetechnologies", ats: "greenhouse", nom: "Peregrine Technologies", marche: "gb" },
  { slug: "crunchyroll", ats: "greenhouse", nom: "Crunchyroll, LLC", marche: "gb" },
  { slug: "penumbrainc", ats: "lever", nom: "Penumbra", marche: "gb" },
  { slug: "avride", ats: "greenhouse", nom: "Avride", marche: "gb" },
  { slug: "carta", ats: "greenhouse", nom: "Carta", marche: "gb" },
  { slug: "kong", ats: "ashby", nom: "Kong", marche: "gb" },
  { slug: "alpaca", ats: "greenhouse", nom: "Alpaca", marche: "gb" },
  { slug: "matchgroup", ats: "lever", nom: "Match Group", marche: "gb" },
  { slug: "replit", ats: "ashby", nom: "Replit", marche: "gb" },
  { slug: "sigmacomputing", ats: "greenhouse", nom: "Sigma Computing", marche: "gb" },
  { slug: "suno", ats: "ashby", nom: "Suno", marche: "gb" },
  { slug: "knowbe4", ats: "greenhouse", nom: "KnowBe4", marche: "gb" },
  { slug: "sothebys", ats: "greenhouse", nom: "Sotheby's", marche: "gb" },
  { slug: "krakentech", ats: "ashby", nom: "Kraken", marche: "gb" },
  { slug: "duolingo", ats: "greenhouse", nom: "Duolingo", marche: "gb" },
  { slug: "peloton", ats: "greenhouse", nom: "Peloton", marche: "gb" },
  { slug: "mixpanel", ats: "greenhouse", nom: "Mixpanel", marche: "gb" },
  { slug: "launchdarkly", ats: "greenhouse", nom: "LaunchDarkly", marche: "gb" },
  { slug: "tailscale", ats: "greenhouse", nom: "Tailscale", marche: "gb" },
  { slug: "lightningai", ats: "greenhouse", nom: "Lightning AI", marche: "gb" },
  { slug: "writer", ats: "ashby", nom: "WRITER", marche: "gb" },
  { slug: "supabase", ats: "ashby", nom: "Supabase", marche: "gb" },
  { slug: "humansignal", ats: "greenhouse", nom: "HumanSignal", marche: "gb" },
  { slug: "virtu", ats: "greenhouse", nom: "Virtu Financial", marche: "gb" },
  { slug: "coram-ai", ats: "ashby", nom: "Coram AI", marche: "gb" },
  { slug: "qualtrics", ats: "greenhouse", nom: "Qualtrics", marche: "gb" },
  { slug: "relex", ats: "greenhouse", nom: "RELEX Solutions", marche: "gb" },
  { slug: "mendix", ats: "lever", nom: "Mendix", marche: "gb" },
  { slug: "clearstreet", ats: "greenhouse", nom: "Clear Street", marche: "gb" },
  { slug: "runway-ml", ats: "ashby", nom: "Runway", marche: "gb" },
  { slug: "verve", ats: "greenhouse", nom: "Verve", marche: "gb" },
  { slug: "mapbox", ats: "ashby", nom: "Mapbox", marche: "gb" },
  { slug: "algolia", ats: "greenhouse", nom: "Algolia", marche: "gb" },
  { slug: "modal", ats: "ashby", nom: "Modal", marche: "gb" },
  { slug: "canarytechnologies", ats: "lever", nom: "Canary Technologies Corp", marche: "gb" },
  { slug: "datacamp", ats: "greenhouse", nom: "DataCamp", marche: "gb" },
  { slug: "tenableinc", ats: "greenhouse", nom: "Tenable, Inc.", marche: "gb" },
  { slug: "commercetools", ats: "greenhouse", nom: "commercetools", marche: "gb" },
  { slug: "hudl", ats: "greenhouse", nom: "Hudl", marche: "gb" },
  { slug: "coupa", ats: "lever", nom: "Coupa Software, Inc.", marche: "gb" },
  { slug: "ironcladhq", ats: "ashby", nom: "Ironclad", marche: "gb" },
  { slug: "koboldmetals", ats: "greenhouse", nom: "KoBold Metals", marche: "gb" },
  { slug: "classpass", ats: "greenhouse", nom: "ClassPass", marche: "gb" },
  { slug: "floqast", ats: "lever", nom: "FloQast", marche: "gb" },
  { slug: "gigaml", ats: "ashby", nom: "Giga", marche: "gb" },
  { slug: "taketwo", ats: "greenhouse", nom: "Take-Two Interactive Software, Inc.", marche: "gb" },
  { slug: "fender", ats: "greenhouse", nom: "Fender", marche: "gb" },
  { slug: "aptura", ats: "ashby", nom: "Aptura", marche: "gb" },
  { slug: "rilla", ats: "ashby", nom: "Rilla", marche: "gb" },
  { slug: "livekit", ats: "ashby", nom: "LiveKit", marche: "gb" },
  { slug: "blacksky", ats: "greenhouse", nom: "BlackSky", marche: "gb" },
  { slug: "censys", ats: "greenhouse", nom: "Censys", marche: "gb" },
  { slug: "coder", ats: "ashby", nom: "Coder", marche: "gb" },
  { slug: "socket", ats: "ashby", nom: "Socket", marche: "gb" },
  { slug: "outreach", ats: "lever", nom: "Outreach", marche: "gb" },
  { slug: "convergentresearch", ats: "lever", nom: "Convergent Research", marche: "gb" },
  { slug: "contentsquare", ats: "lever", nom: "Contentsquare", marche: "gb" },
  { slug: "astronomer", ats: "ashby", nom: "Astronomer", marche: "gb" },
  { slug: "alayacare", ats: "greenhouse", nom: "AlayaCare", marche: "gb" },
  { slug: "behavox", ats: "greenhouse", nom: "Behavox", marche: "gb" },
  { slug: "distyl", ats: "ashby", nom: "Distyl AI", marche: "gb" },
  { slug: "antithesis", ats: "ashby", nom: "Antithesis", marche: "gb" },
  { slug: "pendo", ats: "greenhouse", nom: "Pendo", marche: "gb" },
  { slug: "g2i", ats: "ashby", nom: "G2i Inc.", marche: "gb" },
  { slug: "bazaarvoice", ats: "lever", nom: "Bazaarvoice", marche: "gb" },
  { slug: "triplelift", ats: "greenhouse", nom: "TripleLift", marche: "gb" },
  { slug: "dominodatalab", ats: "greenhouse", nom: "Domino", marche: "gb" },
  { slug: "oscilar", ats: "ashby", nom: "Oscilar", marche: "gb" },
  { slug: "ember", ats: "recruitee", nom: "Ember", marche: "gb" },
  { slug: "contentful", ats: "greenhouse", nom: "Contentful", marche: "gb" },
  { slug: "norm-ai", ats: "ashby", nom: "Norm Ai", marche: "gb" },
  { slug: "airops", ats: "ashby", nom: "AirOps", marche: "gb" },
  { slug: "altanaai", ats: "greenhouse", nom: "Altana", marche: "gb" },
  { slug: "protege", ats: "ashby", nom: "Protege", marche: "gb" },
  { slug: "orkes", ats: "greenhouse", nom: "Orkes", marche: "gb" },
  { slug: "appzen", ats: "lever", nom: "AppZen, Inc.", marche: "gb" },
  { slug: "mercanis", ats: "personio", nom: "Mercanis", marche: "gb" },
  { slug: "prematch-sports-gmbh", ats: "personio", nom: "PREMATCH Sports GmbH", marche: "gb" },
  { slug: "deepl", ats: "ashby", nom: "DeepL", marche: "gb" },
  { slug: "hiya", ats: "ashby", nom: "Hiya", marche: "gb" },
  { slug: "q-ctrl", ats: "lever", nom: "Q-CTRL", marche: "gb" },
  { slug: "rigetti", ats: "lever", nom: "Rigetti Computing", marche: "gb" },
  { slug: "liveeo-gmbh", ats: "personio", nom: "Jobs bei LiveEO GmbH", marche: "gb" },
  { slug: "harrys", ats: "greenhouse", nom: "Harry's", marche: "gb" },
  { slug: "ontic", ats: "ashby", nom: "Ontic", marche: "gb" },
  { slug: "sona", ats: "ashby", nom: "Sona", marche: "gb" },
  { slug: "soundcloud71", ats: "greenhouse", nom: "SoundCloud", marche: "gb" },
  { slug: "obsidiansecurity", ats: "greenhouse", nom: "Obsidian Security", marche: "gb" },
  { slug: "theathletic", ats: "lever", nom: "The Athletic Media Company", marche: "gb" },
  { slug: "signifyd95", ats: "greenhouse", nom: "Signifyd", marche: "gb" },
  { slug: "akur8", ats: "ashby", nom: "Akur8", marche: "gb" },
  { slug: "mattermost", ats: "greenhouse", nom: "Mattermost", marche: "gb" },
  { slug: "olo", ats: "lever", nom: "Olo", marche: "gb" },
  { slug: "immuta", ats: "lever", nom: "Immuta", marche: "gb" },
  { slug: "ideo", ats: "greenhouse", nom: "IDEO", marche: "gb" },
  { slug: "apolloresearch", ats: "lever", nom: "Apollo Research", marche: "gb" },
  { slug: "humaans", ats: "ashby", nom: "Humaans", marche: "gb" },
  { slug: "merantix", ats: "personio", nom: "Merantix", marche: "gb" },
  { slug: "muckrack", ats: "greenhouse", nom: "Muck Rack", marche: "gb" },
  { slug: "brave", ats: "greenhouse", nom: "Brave", marche: "gb" },
  { slug: "axle-careers", ats: "ashby", nom: "Axle Energy", marche: "gb" },
  { slug: "avantarte", ats: "recruitee", nom: "Avant Arte", marche: "gb" },
  { slug: "engineersgate", ats: "greenhouse", nom: "Engineers Gate", marche: "gb" },
  { slug: "fanvue.com", ats: "ashby", nom: "Fanvue", marche: "gb" },
  { slug: "buildkite", ats: "greenhouse", nom: "Buildkite", marche: "gb" },
  { slug: "sumologic", ats: "greenhouse", nom: "Sumo Logic", marche: "gb" },
  { slug: "quantummetric", ats: "lever", nom: "Quantum Metric", marche: "gb" },
  { slug: "patch.io", ats: "ashby", nom: "Patch", marche: "gb" },
  { slug: "ditto", ats: "ashby", nom: "Ditto", marche: "gb" },
  { slug: "anima", ats: "ashby", nom: "Anima", marche: "gb" },
  { slug: "smarkets", ats: "ashby", nom: "Smarkets", marche: "gb" },
  { slug: "splice", ats: "greenhouse", nom: "Splice", marche: "gb" },
  { slug: "pathstream", ats: "greenhouse", nom: "Pathstream", marche: "gb" },
  { slug: "cordial81", ats: "greenhouse", nom: "Cordial Experience Inc.", marche: "gb" },
  { slug: "meticulous", ats: "ashby", nom: "Meticulous", marche: "gb" },
  { slug: "triggerdev", ats: "ashby", nom: "Trigger.dev", marche: "gb" },
  { slug: "pexa", ats: "lever", nom: "PEXA Group", marche: "gb" },
  { slug: "evervault", ats: "ashby", nom: "Evervault", marche: "gb" },
  { slug: "v7labs.com", ats: "ashby", nom: "V7", marche: "gb" },
  { slug: "electric-twin", ats: "lever", nom: "Electric Twin", marche: "gb" },
  { slug: "blacklane", ats: "greenhouse", nom: "BLACKLANE", marche: "gb" },
  { slug: "aurosglobal", ats: "greenhouse", nom: "Auros", marche: "gb" },
  { slug: "voldex", ats: "ashby", nom: "Voldex Games", marche: "gb" },
  { slug: "causalens", ats: "recruitee", nom: "causaLens", marche: "gb" },
  { slug: "pod-network", ats: "ashby", nom: "pod.network", marche: "gb" },
  { slug: "speckle", ats: "ashby", nom: "Speckle", marche: "gb" },
  { slug: "lightdash", ats: "ashby", nom: "Lightdash", marche: "gb" },
  { slug: "ameba", ats: "ashby", nom: "Ameba", marche: "gb" },
  { slug: "tilt", ats: "ashby", nom: "Tilt", marche: "gb" },
  { slug: "materiom", ats: "greenhouse", nom: "Materiom", marche: "gb" },
  { slug: "herdify", ats: "personio", nom: "Herdify", marche: "gb" },
  { slug: "mubit", ats: "ashby", nom: "Mubit", marche: "gb" },
];

export function boardsParAts(nom) {
  return BOARDS.filter((b) => b.ats === nom);
}

// UN TABLEAU SANS `marche` EST D'AVANT QUE LE CHAMP EXISTE
//
// Les quarante-neuf premieres lignes ont ete verifiees a la main, une par
// une, et plusieurs sont des entreprises qui embauchent partout. Elles sont
// donc essayees pour tous les marches : un champ ajoute ne doit jamais
// retirer une ligne d'une recherche qui la trouvait hier.
//
// Pour les suivantes, le marche est ce qui rend l'echelle possible. Une
// recherche a Londres n'a aucune raison de lire les tableaux allemands, et
// c'est la difference entre un registre de cinq cents lignes et un registre
// qui peut en porter des milliers.
//
// Cette fonction est APRES boardsParAts et non avant, parce que les scripts
// de decouverte inserent leurs lignes juste devant celle-la : la chaine
// "];\n\nexport function boardsParAts" est leur point d'ancrage, et y glisser
// quoi que ce soit leur fait refuser d'ecrire.
export function boardsDuMarche(code) {
  const c = String(code || "").toLowerCase();
  return BOARDS.filter((b) => !b.marche || b.marche === c);
}

export function nomDeLEntreprise(slug) {
  const b = BOARDS.find((x) => x.slug === slug);
  return (b && b.nom) || slug;
}
